[package]
name = "fabricaup"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "fabricaup"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
fabricaup-core = { path = "../fabricaup-core" }
flate2.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
zip.workspace = true
